-- Please ensure you already have existing oracle instance or pluggable database (PDB). If not, please create one firstly

-- create tablespace
-- Change DATAFILE/TEMPFILE as required by your configuration
CREATE TABLESPACE OS1DBDATATS DATAFILE '/home/oracle/orcl/OS1DBDATATS.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE PERMANENT;
CREATE TEMPORARY TABLESPACE OS1DBDATATSTEMP TEMPFILE '/home/oracle/orcl/OS1DBDATATSTEMP.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL;

-- create a new user for OS1DB
CREATE USER OS1DB PROFILE DEFAULT IDENTIFIED BY <password> DEFAULT TABLESPACE OS1DBDATATS TEMPORARY TABLESPACE OS1DBDATATSTEMP ACCOUNT UNLOCK;

-- provide quota on all tablespaces with BPM tables
ALTER USER OS1DB QUOTA UNLIMITED ON OS1DBDATATS;
ALTER USER OS1DB DEFAULT TABLESPACE OS1DBDATATS;
ALTER USER OS1DB TEMPORARY TABLESPACE OS1DBDATATSTEMP;

-- allow the user to connect to the database
GRANT CONNECT TO OS1DB;
GRANT ALTER session TO OS1DB;

-- grant privileges to create database objects
GRANT CREATE SESSION TO OS1DB;
GRANT CREATE TABLE TO OS1DB;
GRANT CREATE VIEW TO OS1DB;
GRANT CREATE SEQUENCE TO OS1DB;
GRANT CREATE PROCEDURE TO OS1DB;

-- grant access rights to resolve XA related issues
GRANT SELECT on pending_trans$ TO OS1DB;
GRANT SELECT on dba_2pc_pending TO OS1DB;
GRANT SELECT on dba_pending_transactions TO OS1DB;
GRANT SELECT on DUAL TO OS1DB;
GRANT SELECT on product_component_version TO OS1DB;
GRANT SELECT on USER_INDEXES TO OS1DB;
GRANT EXECUTE ON DBMS_XA TO OS1DB;
EXIT;
