-- Creating DB named: GCDDB 
CREATE DATABASE GCDDB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;

CONNECT TO GCDDB;

-- Create bufferpool 
CREATE BUFFERPOOL GCDDB_1_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL GCDDB_2_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;

-- Create table spaces
CREATE REGULAR TABLESPACE GCDDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL GCDDB_1_32K;

CREATE USER TEMPORARY TABLESPACE GCDDB_TMP_TBS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL GCDDB_2_32K;

-- Grant permissions to DB user
GRANT CREATETAB,CONNECT ON DATABASE TO user <username>;
GRANT USE OF TABLESPACE GCDDATA_TS TO user <username>;
GRANT USE OF TABLESPACE GCDDB_TMP_TBS TO user <username>;
GRANT SELECT ON SYSIBM.SYSVERSIONS to user <username>;
GRANT SELECT ON SYSCAT.DATATYPES to user <username>;
GRANT SELECT ON SYSCAT.INDEXES to user <username>;
GRANT SELECT ON SYSIBM.SYSDUMMY1 to user <username>;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD to user <username>;
GRANT IMPLICIT_SCHEMA ON DATABASE to user <username>;

-- Apply DB tunings
UPDATE DB CFG FOR GCDDB USING LOCKTIMEOUT 30;
UPDATE DB CFG FOR GCDDB USING APPLHEAPSZ 2560;

CONNECT RESET;

-- Notes: After DB be created, please set below setting.
-- db2set DB2_WORKLOAD=FILENET_CM
-- db2set DB2_MINIMIZE_LISTPREFETCH=YES

-- Done creating and tuning DB named: GCDDB