-- Please ensure you already have existing oracle instance or pluggable database (PDB). If not, please create one firstly

-- create tablespace
-- Change DATAFILE/TEMPFILE as required by your configuration
CREATE TABLESPACE BAWDOSDATATS DATAFILE '/home/oracle/orcl/BAWDOSDATATS.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE PERMANENT;
CREATE TEMPORARY TABLESPACE BAWDOSDATATSTEMP TEMPFILE '/home/oracle/orcl/BAWDOSDATATSTEMP.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL;

-- create a new user for BAWDOS
CREATE USER BAWDOS PROFILE DEFAULT IDENTIFIED BY <password> DEFAULT TABLESPACE BAWDOSDATATS TEMPORARY TABLESPACE BAWDOSDATATSTEMP ACCOUNT UNLOCK;

-- provide quota on all tablespaces with BPM tables
ALTER USER BAWDOS QUOTA UNLIMITED ON BAWDOSDATATS;
ALTER USER BAWDOS DEFAULT TABLESPACE BAWDOSDATATS;
ALTER USER BAWDOS TEMPORARY TABLESPACE BAWDOSDATATSTEMP;

-- allow the user to connect to the database
GRANT CONNECT TO BAWDOS;
GRANT ALTER session TO BAWDOS;

-- grant privileges to create database objects
GRANT CREATE SESSION TO BAWDOS;
GRANT CREATE TABLE TO BAWDOS;
GRANT CREATE VIEW TO BAWDOS;
GRANT CREATE SEQUENCE TO BAWDOS;
GRANT CREATE PROCEDURE TO BAWDOS;

-- grant access rights to resolve XA related issues
GRANT SELECT on pending_trans$ TO BAWDOS;
GRANT SELECT on dba_2pc_pending TO BAWDOS;
GRANT SELECT on dba_pending_transactions TO BAWDOS;
GRANT SELECT on DUAL TO BAWDOS;
GRANT SELECT on product_component_version TO BAWDOS;
GRANT SELECT on USER_INDEXES TO BAWDOS;
GRANT EXECUTE ON DBMS_XA TO BAWDOS;
EXIT;