-- Please ensure you already have existing oracle instance or pluggable database (PDB). If not, please create one firstly

-- create tablespace
-- Change DATAFILE/TEMPFILE as required by your configuration
CREATE TABLESPACE CHOSDATATS DATAFILE '/home/oracle/orcl/CHOSDATATS.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE PERMANENT;
CREATE TEMPORARY TABLESPACE CHOSDATATSTEMP TEMPFILE '/home/oracle/orcl/CHOSDATATSTEMP.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL;

-- create a new user for CHOS
CREATE USER CHOS PROFILE DEFAULT IDENTIFIED BY <password> DEFAULT TABLESPACE CHOSDATATS TEMPORARY TABLESPACE CHOSDATATSTEMP ACCOUNT UNLOCK;

-- provide quota on all tablespaces with BPM tables
ALTER USER CHOS QUOTA UNLIMITED ON CHOSDATATS;
ALTER USER CHOS DEFAULT TABLESPACE CHOSDATATS;
ALTER USER CHOS TEMPORARY TABLESPACE CHOSDATATSTEMP;

-- allow the user to connect to the database
GRANT CONNECT TO CHOS;
GRANT ALTER session TO CHOS;

-- grant privileges to create database objects
GRANT CREATE SESSION TO CHOS;
GRANT CREATE TABLE TO CHOS;
GRANT CREATE VIEW TO CHOS;
GRANT CREATE SEQUENCE TO CHOS;
GRANT CREATE PROCEDURE TO CHOS;

-- grant access rights to resolve XA related issues
GRANT SELECT on pending_trans$ TO CHOS;
GRANT SELECT on dba_2pc_pending TO CHOS;
GRANT SELECT on dba_pending_transactions TO CHOS;
GRANT SELECT on DUAL TO CHOS;
GRANT SELECT on product_component_version TO CHOS;
GRANT SELECT on USER_INDEXES TO CHOS;
GRANT EXECUTE ON DBMS_XA TO CHOS;
EXIT;