-- Please ensure you already have existing oracle instance or pluggable database (PDB). If not, please create one firstly

-- create tablespace
-- Change DATAFILE/TEMPFILE as required by your configuration
CREATE TABLESPACE BAWTOSDATATS DATAFILE '/home/oracle/orcl/BAWTOSDATATS.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE PERMANENT;
CREATE TEMPORARY TABLESPACE BAWTOSDATATSTEMP TEMPFILE '/home/oracle/orcl/BAWTOSDATATSTEMP.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL;

-- create a new user for BAWTOS
CREATE USER BAWTOS PROFILE DEFAULT IDENTIFIED BY <password> DEFAULT TABLESPACE BAWTOSDATATS TEMPORARY TABLESPACE BAWTOSDATATSTEMP ACCOUNT UNLOCK;

-- provide quota on all tablespaces with BPM tables
ALTER USER BAWTOS QUOTA UNLIMITED ON BAWTOSDATATS;
ALTER USER BAWTOS DEFAULT TABLESPACE BAWTOSDATATS;
ALTER USER BAWTOS TEMPORARY TABLESPACE BAWTOSDATATSTEMP;

-- allow the user to connect to the database
GRANT CONNECT TO BAWTOS;
GRANT ALTER session TO BAWTOS;

-- grant privileges to create database objects
GRANT CREATE SESSION TO BAWTOS;
GRANT CREATE TABLE TO BAWTOS;
GRANT CREATE VIEW TO BAWTOS;
GRANT CREATE SEQUENCE TO BAWTOS;
GRANT CREATE PROCEDURE TO BAWTOS;

-- grant access rights to resolve XA related issues
GRANT SELECT on pending_trans$ TO BAWTOS;
GRANT SELECT on dba_2pc_pending TO BAWTOS;
GRANT SELECT on dba_pending_transactions TO BAWTOS;
GRANT SELECT on DUAL TO BAWTOS;
GRANT SELECT on product_component_version TO BAWTOS;
GRANT SELECT on USER_INDEXES TO BAWTOS;
GRANT EXECUTE ON DBMS_XA TO BAWTOS;
EXIT;