-- Please ensure you already have existing oracle instance or pluggable database (PDB). If not, please create one firstly

-- create tablespace
-- Change DATAFILE/TEMPFILE as required by your configuration
CREATE TABLESPACE AEOSDATATS DATAFILE '/home/oracle/orcl/AEOSDATATS.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ONLINE PERMANENT;
CREATE TEMPORARY TABLESPACE AEOSDATATSTEMP TEMPFILE '/home/oracle/orcl/AEOSDATATSTEMP.dbf' SIZE 200M REUSE AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL;

-- create a new user for AEOS
CREATE USER AEOS PROFILE DEFAULT IDENTIFIED BY <password> DEFAULT TABLESPACE AEOSDATATS TEMPORARY TABLESPACE AEOSDATATSTEMP ACCOUNT UNLOCK;

-- provide quota on all tablespaces with BPM tables
ALTER USER AEOS QUOTA UNLIMITED ON AEOSDATATS;
ALTER USER AEOS DEFAULT TABLESPACE AEOSDATATS;
ALTER USER AEOS TEMPORARY TABLESPACE AEOSDATATSTEMP;

-- allow the user to connect to the database
GRANT CONNECT TO AEOS;
GRANT ALTER session TO AEOS;

-- grant privileges to create database objects
GRANT CREATE SESSION TO AEOS;
GRANT CREATE TABLE TO AEOS;
GRANT CREATE VIEW TO AEOS;
GRANT CREATE SEQUENCE TO AEOS;
GRANT CREATE PROCEDURE TO AEOS;

-- grant access rights to resolve XA related issues
GRANT SELECT on pending_trans$ TO AEOS;
GRANT SELECT on dba_2pc_pending TO AEOS;
GRANT SELECT on dba_pending_transactions TO AEOS;
GRANT SELECT on DUAL TO AEOS;
GRANT SELECT on product_component_version TO AEOS;
GRANT SELECT on USER_INDEXES TO AEOS;
GRANT EXECUTE ON DBMS_XA TO AEOS;
EXIT;