CONNECT TO proj1;
GRANT CONNECT,DATAACCESS,CREATETAB ON DATABASE TO USER <username> ;
GRANT USE OF TABLESPACE proj1DATA TO user <username> ;
GRANT USE OF TABLESPACE USERTEMP1 TO user <username> ;
CONNECT RESET;