CONNECT TO proj2;
GRANT CONNECT,DATAACCESS,CREATETAB ON DATABASE TO USER <username> ;
GRANT USE OF TABLESPACE proj2DATA TO user <username> ;
GRANT USE OF TABLESPACE USERTEMP1 TO user <username> ;
CONNECT RESET;