-- Creating DB named: aeos
CREATE DATABASE aeos AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;

CONNECT TO aeos;

-- Create bufferpool
CREATE BUFFERPOOL aeos_1_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL aeos_2_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE BUFFERPOOL aeos_3_32K IMMEDIATE SIZE 1024 PAGESIZE 32K;

-- Create table spaces
CREATE LARGE TABLESPACE OSDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL aeos_1_32K;
CREATE LARGE TABLESPACE VWDATA_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL aeos_2_32K;
CREATE USER TEMPORARY TABLESPACE aeos_TMP_TBS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL aeos_3_32K;

-- Grant permissions to DB user
GRANT CREATETAB,CONNECT ON DATABASE TO USER <username>;
GRANT USE OF TABLESPACE OSDATA_TS TO USER <username>;
GRANT USE OF TABLESPACE VWDATA_TS TO USER <username>;
GRANT USE OF TABLESPACE aeos_TMP_TBS TO USER <username>;
GRANT SELECT ON SYSIBM.SYSVERSIONS TO USER <username>;
GRANT SELECT ON SYSCAT.DATATYPES TO USER <username>;
GRANT SELECT ON SYSCAT.INDEXES TO USER <username>;
GRANT SELECT ON SYSIBM.SYSDUMMY1 TO USER <username>;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO USER <username>;
GRANT IMPLICIT_SCHEMA ON DATABASE TO USER <username>;
CREATE SCHEMA <username> AUTHORIZATION <username>;

-- Apply DB tunings
UPDATE DB CFG FOR aeos USING LOCKTIMEOUT 30;
UPDATE DB CFG FOR aeos USING LOGFILSIZ 6000; 

-- Notes: Please verify below environment configuration settings were applied to the Db2 server.
-- db2set DB2_WORKLOAD=FILENET_CM
-- db2set DB2_MINIMIZE_LISTPREFETCH=YES

CONNECT RESET;

-- Done creating and tuning DB named: aeos
