-- Creating DB named: APPDB 
CREATE DATABASE APPDB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32768;

-- connect to the created database:
CONNECT TO APPDB;

-- Create bufferpool and tablespaces
CREATE BUFFERPOOL DBASBBP IMMEDIATE SIZE 1024 PAGESIZE 32K;
CREATE REGULAR TABLESPACE APPENG_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE DROPPED TABLE RECOVERY ON BUFFERPOOL DBASBBP;
CREATE USER TEMPORARY TABLESPACE APPENG_TEMP_TS PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL DBASBBP;

-- grant access rights to the tablespaces
GRANT USE OF TABLESPACE APPENG_TS TO USER <username>;
GRANT USE OF TABLESPACE APPENG_TEMP_TS TO USER <username>;

GRANT DBADM ON DATABASE TO USER <username>;

CONNECT RESET;
-- Done creating and tuning DB named: APPDB