-- Creating DB named: ODMDB
CREATE DATABASE ODMDB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32 K;

-- connect to the created database:
CONNECT TO ODMDB;

-- Create bufferpool and tablespaces
CREATE BUFFERPOOL ODMDB_BP32K SIZE 2000 PAGESIZE 32K;
CREATE TABLESPACE ODMDB_RESDWTS PAGESIZE 32K BUFFERPOOL ODMDB_BP32K;
CREATE SYSTEM TEMPORARY TABLESPACE ODMDB_RESDWTMPTS PAGESIZE 32K BUFFERPOOL ODMDB_BP32K;
CREATE SCHEMA <username> AUTHORIZATION <username>;

CONNECT RESET;